spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}
    username: ${mysql.username}
    password: ${mysql.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      database: ${redis.database}
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的转换
